### ISSUE TITLE
Missing binaries on the release?

### ISSUE THREAD

**Issue by ctron** [8go/matrix-commander-rs#43]
I noticed that there a .sha256 files on the release, but no binaries. Is that on purpose? Or are they simply missing?

**Comment by 8go** [comment]
Sometimes the build-action fails but I am not sure why. It might be time limit or a build resource limit on the side of Github. If the automatic build action fails, then files are missing in the release. It is not on purpose. But you can always get it from `https://crate.io`.

**Comment by Benjamin-Loison** [comment]
For reference [v0.1.32](https://github.com/8go/matrix-commander-rs/releases/tag/v0.1.32) is the last release having the mentioned issue and [here is the associated GitHub action](https://github.com/8go/matrix-commander-rs/actions/runs/5119980663).
