### ISSUE TITLE
Bug: Hide password when providing it

### ISSUE THREAD

**Issue by Benjamin-Loison** [8go/matrix-commander-rs#68]
When executing:
```
matrix-commander-rs --login password
```
we get at some point:
```
Enter Matrix password for this user: 
```
but surprisingly, hoping no one is behind your shoulder, your password is written in the shell in plaintext, giving:
```
Enter Matrix password for this user: YOUR_PASSWORD
```

**Comment by 8go** [comment]
This has been fixed. @Benjamin-Loison please get the latest release.
