### ISSUE TITLE
Is this even working?

### ISSUE THREAD

**Issue by hiiamboris** [8go/matrix-commander-rs#92]
After a few days of `cargo build` compiling `ruma-common` it just says:

``  process didn't exit successfully: `rustc --crate-name ruma_common --edition=2021 /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ruma-common-0.10.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=186 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="api"' --cfg 'feature="canonical-json"' --cfg 'feature="client"' --cfg 'feature="compat"' --cfg 'feature="default"' --cfg 'feature="events"' --cfg 'feature="markdown"' --cfg 'feature="pulldown-cmark"' --cfg 'feature="rand"' --cfg 'feature="server"' --cfg 'feature="unstable-msc2448"' --cfg 'feature="unstable-msc2676"' --cfg 'feature="unstable-msc2677"' -C metadata=31aa010fdb830bd5 -C extra-filename=-31aa010fdb830bd5 --out-dir /root/matrix-commander-rs/target/debug/deps -L dependency=/root/matrix-commander-rs/target/debug/deps --extern base64=/root/matrix-commander-rs/target/debug/deps/libbase64-938f34a52bd7cef6.rmeta --extern bytes=/root/matrix-commander-rs/target/debug/deps/libbytes-a92bbd776b3d42e5.rmeta --extern form_urlencoded=/root/matrix-commander-rs/target/debug/deps/libform_urlencoded-dc53efd1de5d17b2.rmeta --extern http=/root/matrix-commander-rs/target/debug/deps/libhttp-89621b74240ffeda.rmeta --extern indexmap=/root/matrix-commander-rs/target/debug/deps/libindexmap-6cffbfc865f431ca.rmeta --extern itoa=/root/matrix-commander-rs/target/debug/deps/libitoa-d4abb74660950598.rmeta --extern js_int=/root/matrix-commander-rs/target/debug/deps/libjs_int-369b1ebb8f7a70f5.rmeta --extern js_option=/root/matrix-commander-rs/target/debug/deps/libjs_option-72e5dfb1027fc92f.rmeta --extern percent_encoding=/root/matrix-commander-rs/target/debug/deps/libpercent_encoding-72ba7a39f568a92e.rmeta --extern pulldown_cmark=/root/matrix-commander-rs/target/debug/deps/libpulldown_cmark-3e3593192c4cd39a.rmeta --extern rand_crate=/root/matrix-commander-rs/target/debug/deps/librand-aec2a043dd8d8f83.rmeta --extern regex=/root/matrix-commander-rs/target/debug/deps/libregex-5473a77769db4c75.rmeta --extern ruma_identifiers_validation=/root/matrix-commander-rs/target/debug/deps/libruma_identifiers_validation-accfd1a486dd7b51.rmeta --extern ruma_macros=/root/matrix-commander-rs/target/debug/deps/libruma_macros-1e531ed4b2afdc0e.so --extern serde=/root/matrix-commander-rs/target/debug/deps/libserde-5d74320d1378dcd8.rmeta --extern serde_json=/root/matrix-commander-rs/target/debug/deps/libserde_json-ec225e2c3c9b41bc.rmeta --extern thiserror=/root/matrix-commander-rs/target/debug/deps/libthiserror-aea9a349ecdae64e.rmeta --extern tracing=/root/matrix-commander-rs/target/debug/deps/libtracing-e93690d9178d5d6b.rmeta --extern url=/root/matrix-commander-rs/target/debug/deps/liburl-fb355140f7f797c4.rmeta --extern uuid=/root/matrix-commander-rs/target/debug/deps/libuuid-3b5750b4540448c7.rmeta --extern wildmatch=/root/matrix-commander-rs/target/debug/deps/libwildmatch-288a4fd984e4e8f4.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)``

If this is actually working, binaries would be appreciated.

**Comment by 8go** [comment]
It works for me. Did emoji verification and sending messages. 

Just did an update of Rust to 1.78, Recompiled on Rust 1.78. Also works without any warnings or errors.

**Comment by 8go** [comment]
see issue #93
