### ISSUE TITLE
Enhancement: Create binaries

### ISSUE THREAD

**Issue by 8go** [8go/matrix-commander-rs#93]
Some people want a binary:

If you want a binary version, you could do this: 

- fork this repo
- write a github action to 

1. create a new release, 
2. create the desired binary and 
3. place the binary into the new release

- once tested and this creates a new release with the expected binary whenever you do a `git push` then make PR to my repo
- I accept the PR, and if it works correctly, each time I do a `git push` it should create a new binary on the release page available to everybody

**Comment by Benjamin-Loison** [comment]
Just to make sure what you mean by *to do a `pull`*, you mean that the GitHub action is triggered when the pull request is merged, right?

**Comment by 8go** [comment]
Sorry, I must have been distracted when I wrote the above note. I meant "push" (not "pull"). The action should be triggered on "git push". Sorry. 

I edited the above note to fix it.

**Comment by 8go** [comment]
@Benjamin-Loison 

2 binaries for v0.4.0 are available (as an exception) in the releases.

**Comment by 8go** [comment]
The project now has a Github Action workflow that generates one binary: linux x86_64
Starting with version v0.9.3

**Comment by 8go** [comment]
3 binaries are now created automatically.

Creating binaries for Microsoft and Apple is not possible due to their OS licenses.

Closing issue.
